[package]
name = "sound-app"
version = "0.0.1"
description = "Sound Recorder desktop app"
authors = []
license = ""
repository = ""
edition = "2021"
rust-version = "1.77.2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "sound_app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.6.3", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
tauri = { version = "2.11.6", features = [] }
tauri-plugin-log = "2"
libpulse-binding = "2"
libpulse-simple-binding = "2"
hound = "3.5.1"
chrono = "0.4.45"
fs4 = "1.1.0"
